image: ruby:latest

variables:
  JEKYLL_ENV: gitlab
  LC_ALL: ru_RU.UTF-8

before_script:
  - gem install bundler
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

build:
  stage: build
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


