lang: ru-RU
title: Сайт FSA
url: https://tavda.org
sass:
  sass_dir: _scss
  style: compressed
permalink: /:title
timezone: Asia/Novosibirsk
plugins:
  - jekyll-redirect-from
exclude:
  - jekyll.sh
  - CNAME

