baseURL = "https://tavda.net/"
locale = "ru-RU"
title = "Сайт FSA"
timezone = "Asia/Novosibirsk"
uglyURLs = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "sitemap"]
  section = ["HTML", "RSS"]

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  description = "Это мой персональный сайт"
  author = "Сергей Федотов (FSA)"
